### PR TITLE
Added sort_dicts argument to my_safe_repr

### PR DESCRIPTION
**Pull request by jhaiduce**
This PR makes deformdemo work with newer versions of Python. sort_dicts is a required argument of pprint._safe_repr in newer versions of Python.

### CODE REVIEW

**Comment by stevepiercy** [comment]
This PR does not work on supported versions of Python, including 3.6. Which newer versions of Python is this supposed to work on? We currently have an [open PR in Deform](https://github.com/Pylons/deform/pull/400) where all tests pass on Python 3.5-3.8 and PyPy 3.

**Comment by jhaiduce** [comment]
This works on Python 3.8.3. 

> This PR does not work on supported versions of Python, including 3.6. Which newer versions of Python is this supposed to work on?

This works on Python 3.8.3 (Specifically, I'm using the python that ships with Fedora 32).

> We currently have an [open PR in Deform](https://github.com/Pylons/deform/pull/400) where all tests pass on Python 3.5-3.8 and PyPy 3.

That PR fails on 3.8.3 in the same way as the master branch:

```
  File "/home/jhaiduce/Development/deform/deformdemo_functional_tests/deformdemo/__init__.py", line 77, in my_safe_repr
    return pprint._safe_repr(obj, context, maxlevels, level)
TypeError: _safe_repr() missing 1 required positional argument: 'sort_dicts'
```

**Comment by stevepiercy** [comment]
I apologize for the current state of Deform under development. We're working at the speed of open source volunteers.

The current `master` branch build on Travis has been failing for some time. Instead please test the branch that is in the open PR, which I will be merging to `master` soon. Then you won't have to support Python 2 as well.

If you run tests locally with tox to run tests on all supported versions of Python, coverage, and lint, then you might have an easier time instead of waiting for Travis. Let me know if you need any help setting that up. We have [some docs that are under review that can help](https://github.com/Pylons/deform/pull/402), too.

**Comment by jhaiduce** [comment]
> I apologize for the current state of Deform under development. We're working at the speed of open source volunteers.

I totally understand, I'm working on this in my free time too.

> The current `master` branch build on Travis has been failing for some time. Instead please test the branch that is in the open PR, which I will be merging to `master` soon. Then you won't have to support Python 2 as well.

I'll try rebasing against that branch then.

> If you run tests locally with tox to run tests on all supported versions of Python, coverage, and lint, then you might have an easier time instead of waiting for Travis. Let me know if you need any help setting that up. We have [some docs that are under review that can help](https://github.com/Pylons/deform/pull/402), too.

Thanks, I'll try using tox. I was just using the script run-selenium-tests.bash script and didn't know about tox.

**Comment by jhaiduce** [comment]
I updated this PR so it's based on the current master branch, and also implemented some fixes so it still works in python 3.6 and earlier.

I noticed that tox.ini currently only runs the functional tests on python 3.6, so the error in python 3.8 that this is intended to fix does not occur in tests unless you either 

- Change tox.ini to run the functional tests on 3.8, or
- Run run-selenium-tests.bash manually.

**Comment by stevepiercy** [comment]
@jhaiduce thanks for this PR! I'll review it over the weekend.

I think that we should add new testing environments for the functional tests to [align with those on which we test Deform 3.0](https://github.com/Pylons/deform/blob/master/.travis.yml), currently 3.5-3.8 and pypy3. I would also add allowed failures on [Python 3.9](https://www.python.org/dev/peps/pep-0596/#schedule) to make us aware of what's coming without blocking releases. That can be a separate PR or included with this one.

Finally utility environments, such as coverage, lint, etc., should be bumped to the latest stable Python 3.8 release.

**Comment by stevepiercy** [comment]
@jhaiduce I just noticed that you had opened the PR against the wrong branch, `drop-py27-py34`, so I changed it `master`. Would you please review the [proposed file changes](https://github.com/Pylons/deformdemo/pull/67/files) to ensure that this is the change you intend?

**Comment by jhaiduce** [comment]
Changes look correct to me.

**Comment by stevepiercy** [comment]
Thank you! One more thing, would you please sign https://github.com/Pylons/deformdemo/blob/master/CONTRIBUTORS.txt and push to this PR? Then I can merge.

As far as expanding the testing environments, if you would like to take that on, I would greatly appreciate it. If you need help with setting up multiple Pythons, I can lend a hand.

**Comment by jhaiduce** [comment]
> Thank you! One more thing, would you please sign https://github.com/Pylons/deformdemo/blob/master/CONTRIBUTORS.txt and push to this PR? Then I can merge.

Done. (I also added an explanatory comment to my changes to __init__.py.)

> As far as expanding the testing environments, if you would like to take that on, I would greatly appreciate it. If you need help with setting up multiple Pythons, I can lend a hand.

I'll get back to you on that. I want to look more closely at your earlier comment to get a better idea what would be involved.

**Comment by jhaiduce** [comment]
> As far as expanding the testing environments, if you would like to take that on, I would greatly appreciate it. If you need help with setting up multiple Pythons, I can lend a hand.

I'd be happy to help with this, but I see you've already committed some related changes to master and I'm not sure what needs to be done next.

**Comment by stevepiercy** [comment]
I was on a mission last night. 😄  If you find anything else you want to work on in either deform or deformdemo, I'm triaging issues and pull requests, working from most recent to oldest, and tagging them with either the 3.0 or 3.1 milestone. I especially could use another pair of eyes on the READMEs and contributing documents for setting up the environment to be a contributor.
